package minesweeper

fun main() {
    print(
        """
            .x.......
            ....xx...
            ..x......
            x........
            ...x..x..
            ........x
            .........
            .....x...
            .......x.
        """.trimIndent()
    )
}
